import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { SearchResult, Jurisdiction } from '@/data/types';
import { getJurisdictionLabel } from '@/data/legalDatabase';
import { getCategoryLabel } from '@/lib/searchEngine';

export function exportResultsToPdf(
  results: SearchResult[],
  query: string,
  jurisdiction: Jurisdiction
) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('TheRightLaw — Legal Discovery Report', pageWidth / 2, 20, { align: 'center' });

  // Subtitle
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(120, 120, 120);
  doc.text('This is NOT legal advice. Consult a qualified legal professional.', pageWidth / 2, 27, { align: 'center' });

  // Metadata
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  const meta = [
    `Jurisdiction: ${getJurisdictionLabel(jurisdiction)}`,
    `Date: ${new Date().toLocaleDateString()}`,
    `Query: "${query}"`,
  ];
  let y = 36;
  meta.forEach((line) => {
    doc.text(line, 14, y);
    y += 6;
  });

  y += 4;

  // Results
  results.forEach((result, idx) => {
    if (y > 260) {
      doc.addPage();
      y = 20;
    }

    // Act header
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(`${idx + 1}. ${result.act.name} (${result.act.year})`, 14, y);
    y += 6;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(80, 80, 80);
    doc.text(`Category: ${getCategoryLabel(result.categoryMatch)} | Confidence: ${result.confidence}% | ${result.matchType === 'exact' ? 'Applicable' : 'Related'}`, 14, y);
    y += 5;

    if (result.aiExplanation) {
      doc.setTextColor(60, 100, 60);
      const explanationLines = doc.splitTextToSize(`AI: ${result.aiExplanation}`, pageWidth - 28);
      doc.text(explanationLines, 14, y);
      y += explanationLines.length * 4 + 2;
    }

    doc.setTextColor(0, 0, 0);

    // Summary
    const summaryLines = doc.splitTextToSize(result.act.summary, pageWidth - 28);
    doc.text(summaryLines, 14, y);
    y += summaryLines.length * 4 + 2;

    // Sections table
    if (result.matchedSections.length > 0) {
      autoTable(doc, {
        startY: y,
        head: [['Section', 'Title', 'Summary']],
        body: result.matchedSections.map((s) => [
          s.sectionNumber,
          s.title,
          s.summary.length > 100 ? s.summary.slice(0, 100) + '...' : s.summary,
        ]),
        styles: { fontSize: 8, cellPadding: 2 },
        headStyles: { fillColor: [34, 49, 74] },
        margin: { left: 14, right: 14 },
        theme: 'grid',
      });
      y = (doc as any).lastAutoTable.finalY + 8;
    }

    // Source
    doc.setFontSize(8);
    doc.setTextColor(0, 80, 160);
    doc.text(`Source: ${result.act.sourceUrl}`, 14, y);
    doc.setTextColor(0, 0, 0);
    y += 10;
  });

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by TheRightLaw — Legal Discovery Engine. Not legal advice.', pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });

  doc.save(`TheRightLaw_${jurisdiction}_${Date.now()}.pdf`);
}
